### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by SyedAmeeruddin** [steve2/django-angular-electron#1]
Is this for python 2 or python 3?

**Comment by SyedAmeeruddin** [comment]
Thanks.But during installation i got these issues.Please go through and kindly resolve
![2018-08-12 1](https://user-images.githubusercontent.com/33616209/43995724-f593a776-9dd0-11e8-99e1-79430f039983.png)
![2018-08-12 2](https://user-images.githubusercontent.com/33616209/43995725-f5d742d8-9dd0-11e8-83a2-20b7a863559c.png)

**Comment by steve2** [comment]
You need to install 'bower' and a LESS compiler ('lessc'). I dont actively maintain this but if I have time I'll add those to the setup.

**Comment by SyedAmeeruddin** [comment]
I have tried to install them but i got compatibility issues and weird errors.Thanks for the project but a completed one will give you good reputation.

**Comment by SyedAmeeruddin** [comment]
Even i installed bower and lessc 
![elec2](https://user-images.githubusercontent.com/33616209/43999360-c08b6a3e-9e28-11e8-91f4-98c9b678b592.png)
![2018-08-12 4](https://user-images.githubusercontent.com/33616209/43999366-e2530ea6-9e28-11e8-8dde-320d9e3d7a7c.png)
![2018-08-12 5](https://user-images.githubusercontent.com/33616209/43999367-e2852d0a-9e28-11e8-8cfc-4f84ef112f33.png)

**Comment by steve2** [comment]
Its still failing because it cannot find `lessc`. It shouldnt be terribly difficult to track down why.

**Comment by SyedAmeeruddin** [comment]
Please debug it.I have gone through a lot

**Comment by steve2** [comment]
You have to install `lessc` with `npm` not `pip`. This can be done with:

```
npm install less
```

I've added the following installations to the `setup.py` script:

```
pip install virtualenv
npm install bower
npm install less
```
