### ISSUE TITLE
To executable 

### ISSUE THREAD

**Issue by ssekuwanda** [steve2/django-angular-electron#3]
I wish this had the final stage of making an exe file, I have tried but failed

**Comment by steve2** [comment]
That would be cool. If I have time I may look into it.

**Comment by steve2** [comment]
I have looked at how to build an Electron application into a binary, and it looks like the `electron-packager` tool is what does it. This can be used simply like:

```
npm install electron-packager -g
electron-packager .\client "App Name"
```

This builds a directory such as `App Name-win32-x64` in the directory where `electron-packager` was invoked (in the above example, it would be the root of the repository).

I've added this to the `build.py` script, with the additional `electron-packager` tool being installed in `setup.py`. To get the update, just do `python setup.py --skip-server --skip-client` and it will install the global dependencies for you.
